### ISSUE TITLE
Mobile view Logo stretched horizontally (On iPhone 7 Safari)

### ISSUE THREAD

**Issue by cchu70** [HackGT/hackgt7-website#1]

**Comment by cchu70** [comment]
![Uploading IMG_0582 2.PNG…]()

**Comment by cchu70** [comment]
My bad

**Comment by cchu70** [comment]
![IMG_0582 2](https://user-images.githubusercontent.com/34669546/86145498-9be02f00-babc-11ea-969d-3c10fd0ac699.PNG)

**Comment by Stephanie-A** [comment]
I'm pretty sure Mary and I discussed that this was fine, but I'll ask her.

**Comment by cchu70** [comment]
![ezgif com-optimize](https://user-images.githubusercontent.com/34669546/86147437-04301000-babf-11ea-850c-938cfe83ae0b.gif)

It can be pretty bad on desktop when you change the window sizes

**Comment by 1ntEgr8** [comment]
ah i see the issue

`height` has been set to `110vh`. never set viewport units for images without setting an appropriate width units

@Stephanie-A

**Comment by Stephanie-A** [comment]
> ah i see the issue
> 
> `height` has been set to `110vh`. never set viewport units for images without setting an appropriate width units
> 
> @Stephanie-A

Thanks!!
