### ISSUE TITLE
FAQ: only first questions block misaligned

### ISSUE THREAD

**Issue by cchu70** [HackGT/hackgt7-website#13]
![IMG_0639](https://user-images.githubusercontent.com/34669546/88561450-0bcad200-cff5-11ea-9d8a-1309a2d7c02d.PNG)

**Comment by Stephanie-A** [comment]
@cchu70 what phone and what browser? I could've sworn I fixed this problem

**Comment by ayush-goyal** [comment]
Happens for me too, iphone Safari

**Comment by Stephanie-A** [comment]
Which iphone @ayush-goyal ?

**Comment by ayush-goyal** [comment]
iphone 11
