### ISSUE TITLE
The bottle image is blurry

### ISSUE THREAD

**Issue by ayush-goyal** [HackGT/hackgt7-website#15]
The bottle image above the letter gets very big and kind of blurry. It could be fixed by using a higher res image, or maybe by making the image not get as big? Personally, I feel like I have to scroll a lot to get from sponsors section to the letter section. This is not really that high priority but
<img width="1437" alt="Screen Shot 2020-07-27 at 12 04 16 PM" src="https://user-images.githubusercontent.com/8273038/88564668-7bdf5500-d001-11ea-90b3-0548a80ba783.png">

**Comment by 1ntEgr8** [comment]
having a higher res image results in poor performance during scaling. the image is fading out as you scroll, so i think we'll be fine
