### ISSUE TITLE
Misplaced FAQ lightbulb

### ISSUE THREAD

**Issue by evan10s** [HackGT/hackgt7-website#18]
Via @mjkaufer, he opened the link to the site in Messenger's built-in browser and this happened

![received_1401818560018430](https://user-images.githubusercontent.com/5790137/88566391-ee513480-d003-11ea-8e66-6ba75020dfe2.png)

**Comment by Stephanie-A** [comment]
@evan10s can you check again? Seems like @1ntEgr8 pushed a fix:

https://github.com/HackGT/hackgt7-website/issues/16

**Comment by Stephanie-A** [comment]
Fixed from #16
