### ISSUE TITLE
Assets still cut off in About page

### ISSUE THREAD

**Issue by sarahdahippo-zz** [HackGT/hackgt7-website#20]
I'm using a Lenovo ThinkPad X1 Carbon Gen 7 for reference!

![Screenshot (53)](https://user-images.githubusercontent.com/55326610/88569540-26d92880-d06d-11ea-8f10-b3d8ff887bf1.png)

**Comment by 1ntEgr8** [comment]
@sarahdahippo  can you try now?

**Comment by sarahdahippo-zz** [comment]
The controller asset looks great now! But the horizontal asset is still (slightly) cut off:

![Screenshot (55)](https://user-images.githubusercontent.com/55326610/88613707-a9d79e80-d0c0-11ea-8e23-afbe71d15a88.png)
![Screenshot (57)](https://user-images.githubusercontent.com/55326610/88613711-aba16200-d0c0-11ea-9f57-011913c383b0.png)

If I finish scrolling horizontally and start to scroll down (from the About page to Tracks) though, I can see the entire asset so it's not too huge of a problem.

![Screenshot (58)](https://user-images.githubusercontent.com/55326610/88613925-34200280-d0c1-11ea-8304-9046a3b02792.png)
