### ISSUE TITLE
Gradient appears over entire webpage instead of the screen on iPad

### ISSUE THREAD

**Issue by blancazhang** [HackGT/hackgt7-website#21]
Device: iPad Pro 12.9" (2732 x 2048 px)
Browser: Google Chrome

On Google Chrome for iPad, the background gradient of the website extends the entirety of the length of the site, so that the home page is completely blue.  The gradient is shown when you scroll through, and then the last page (dear hacker) is green.

![IMG_0109](https://user-images.githubusercontent.com/40508348/88571659-02992f80-d00c-11ea-8a4b-d95df32ec2ed.PNG)
![IMG_0111](https://user-images.githubusercontent.com/40508348/88571647-fd3be500-d00b-11ea-9d41-15fa4e430ada.PNG)

**Comment by 1ntEgr8** [comment]
Looks like a safari quirk, couldn't really find a fix in time. Will take note for next year!
