### ISSUE TITLE
Mac 15in About section not horizontally centered?

### ISSUE THREAD

**Issue by cchu70** [HackGT/hackgt7-website#23]
<img width="1728" alt="Screen Shot 2020-07-27 at 11 07 09 AM" src="https://user-images.githubusercontent.com/34669546/88576604-4f303b00-d00b-11ea-82e5-32764303d97a.png">

the content stays at this level until I finish scrolling (horizontally) through the whole section

**Comment by 1ntEgr8** [comment]
should be fixed now!
