### ISSUE TITLE
MLH link doesn't seem to direct properly to MLH 2021 season event

### ISSUE THREAD

**Issue by cchu70** [HackGT/hackgt7-website#24]
Clicking the banner right now goes here: https://mlh.io/seasons/na-2021/events?utm_source=na-hackathon&utm_medium=TrustBadge&utm_campaign=2021-season&utm_content=white

As opposed to here: https://mlh.io/seasons/2021/events (which is where I think it should be redirecting)

On Mac 13 inch chrome

**Comment by Stephanie-A** [comment]
I will check out what this is supposed to link to

**Comment by Stephanie-A** [comment]
Okay so according to the brand guide, we're supposed to send it there:

https://mlh.io/brand-guidelines
