### ISSUE TITLE
Menu of mentor page overlaps with content

### ISSUE THREAD

**Issue by jlatour3** [HackGT/hackgt7-website#33]
If a participant is scrolling through the mentor page instead of clicking the section headers in the menu, the menu overlaps with the section content. Not sure if we're just assuming a participant is just going to use the menu.

<img width="966" alt="image" src="https://user-images.githubusercontent.com/46651129/89241875-1aede900-d5ce-11ea-83f4-43f7ff1b69d8.png">

**Comment by 1ntEgr8** [comment]
i don't think it matters now, but @mohandodda0 can we close this issue?

**Comment by mohandodda0** [comment]
Yeah go ahead
