### ISSUE TITLE
Weird periods in mentorship site

### ISSUE THREAD

**Issue by blancazhang** [HackGT/hackgt7-website#35]
From "Mentors for Emerging Hackers Team" section:
"Be matched to 1-2 emerging hacker teams based on their goals and your expertise at the beginning of the eve.nt
Check-in with team at least once each day of the hackathon (3 meeting.s)"

<img width="995" alt="Screen Shot 2020-08-28 at 9 57 14 AM" src="https://user-images.githubusercontent.com/40508348/91574608-315d3b00-e915-11ea-8280-05de523736df.png">

**Comment by 1ntEgr8** [comment]
@blancazhang updated cms. the issue should be fixed
