### ISSUE TITLE
Zoom issues

### ISSUE THREAD

**Issue by saachiw** [HackGT/hackgt7-website#7]
Not sure how exactly to explain this but when I scroll past the "Welcome to a new experience" and the bottle with the letter the zoom is really long and it's not smooth at all, it seems really abrupt

**Comment by evan10s** [comment]
^ upvote, also, when I view the site on mobile (Chrome, Android 10), the Welcome to a New Experience title is very abrupt.  It kinda stops in place (it takes me 2-3 "swipes" before anything happens) so it seems like you reached the bottom of the page and idk if I would have known to keep scrolling if I wasn't aware there was more content.  Also the zoomed in text doesn't fade out on mobile soon enough (will send a screenshot)

The behavior of Welcome to a new experience on mobile just in general is very wonky, especially if you scroll up and down repeatedly

**Comment by evan10s** [comment]
The first time I scrolled down:
![Screenshot_20200727-005628](https://user-images.githubusercontent.com/5790137/88504978-29238000-cfa4-11ea-9c8a-ca3f86a5696b.png)

Scrolling back up:
![Screenshot_20200727-005639](https://user-images.githubusercontent.com/5790137/88504977-29238000-cfa4-11ea-9c0e-ab5ca7827a91.png)

Going down again:
![Screenshot_20200727-005645](https://user-images.githubusercontent.com/5790137/88504975-29238000-cfa4-11ea-852a-97825eeb8a76.png)

**Comment by 1ntEgr8** [comment]
@evan10s @saachiw i've seen this issue with safari as well. i think it'll be best to turn off scroll based animations for mobile.

**Comment by saachiw** [comment]
sounds good - it is an issue on safari on mac as well but not on chrome, idk if there is a good way to fix that
