### ISSUE TITLE
"dear hacker" Letter: ending "with <3, hackgt" too large and close to the bottom

### ISSUE THREAD

**Issue by cchu70** [HackGT/hackgt7-website#8]
<img width="827" alt="Screen Shot 2020-07-26 at 11 19 46 PM" src="https://user-images.githubusercontent.com/34669546/88503221-a1834480-cf96-11ea-929f-cabe65b5adc8.png">

For a quick fix, I don't think it's necessary to have it right justified. It can be same font size and left justified, added to the letter content

**Comment by cchu70** [comment]
Also, the font size of the "Dear Hacker" header is much bigger than the other headers for faq, tracks, etc.

**Comment by Stephanie-A** [comment]
Fixed in latest push
